spring.application.name=ProductService

# Sets default logging level for entire application (shows INFO, WARN, ERROR logs)
logging.level.root=INFO

# Enables very detailed request/response and handler mapping logs for Spring Web layer
logging.level.org.springframework.web=TRACE

# Logs all SQL queries executed by Hibernate
logging.level.org.hibernate.SQL=DEBUG

# Logs actual parameter values bound to SQL queries
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Prints SQL queries to console (basic query display)
spring.jpa.show-sql=true

# Formats SQL queries in readable multi-line style
spring.jpa.properties.hibernate.format_sql=true
